version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-area
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./nell_backend:/app
    env_file:
      - .env