version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: nell_backend/Dockerfile
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./nell_backend:/app
    env_file:
      - .env
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=3306
      - DATABASE_NAME=nell_db
      - DATABASE_USER=nell
      - DATABASE_PASSWORD=nell2301$

# import os
#
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': os.getenv('DATABASE_NAME', 'nell_db'),
#        'USER': os.getenv('DATABASE_USER', 'root'),
#        'PASSWORD': os.getenv('DATABASE_PASSWORD', 'nell2301$'),
#        'HOST': os.getenv('DATABASE_HOST', 'localhost'),
#        'PORT': os.getenv('DATABASE_PORT', '3306'),
#    }
#}