services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-area
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./nell_backend:/app
    env_file:
      - .env

  flutter:
    build:
      context: ./area
      dockerfile: Dockerfile
    image: flutter-web
    container_name: flutter_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./area:/area
    working_dir: /area
    command: flutter run -d web-server --web-port 3000 --web-hostname 0.0.0.0