# Generated by Django 5.1.1 on 2024-10-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueskypostreaction',
            name='bluesky_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blueskypostreaction',
            name='bluesky_handle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blueskypostreaction',
            name='bluesky_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twitchliveaction',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twitchliveaction',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twitchliveaction',
            name='twitch_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
