# Generated by Django 5.1.1 on 2024-10-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchs', '0002_blueskypostreaction_bluesky_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueskypostreaction',
            name='bluesky_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
