# Generated by Django 5.1.1 on 2024-10-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitchs', '0003_blueskypostreaction_bluesky_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueskypostreaction',
            name='bluesky_access_token',
        ),
    ]
