# Generated by Django 5.1.1 on 2024-10-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_socialuser_delete_usertoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialuser',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='socialuser',
            name='provider_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='socialuser',
            unique_together={('provider_username', 'provider', 'provider_id')},
        ),
    ]
