# Generated by Django 5.1.1 on 2024-11-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailreceivedaction',
            name='access_token',
        ),
        migrations.AlterField(
            model_name='spotifysongreaction',
            name='song_uri',
            field=models.CharField(default='spotify:track:4KYS9GK68yeuUJ8vJfPxrq', max_length=100),
        ),
    ]
