name: area
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^5.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ClashGrotesk
      fonts:
        - asset: assets/fonts/ClashGrotesk-Variable.ttf
  assets:
    - assets/images/illustration-1.png
    - assets/images/illustration-2.png
    - assets/images/google.png
    - assets/images/github.png
    - assets/images/facebook.png
    - assets/images/spotify.png
    - assets/images/twitch.png
    - assets/images/deezer.png
    - assets/images/microsoft.png
