name: area
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^5.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  url_launcher: ^6.1.10
  tuple: ^2.0.0
  shared_preferences: ^2.3.2
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ClashGrotesk
      fonts:
        - asset: assets/fonts/ClashGrotesk-Variable.ttf
  assets:
    - assets/images/illustration-1.png
    - assets/images/illustration-2.png
    - assets/images/google.png
    - assets/images/github.png
    - assets/images/facebook.png
    - assets/images/spotify.png
    - assets/images/twitch.png
    - assets/images/microsoft.png
    - assets/vectors/
