name: repo_mirroring

on:
  push:
    branches: main

jobs:
  to_gitlab:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2027/B-DEV-500-BER-5-1-area-etienne.namur.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
