name: repo_mirroring

on:
  push:
    branches:
      - '**'  # This will trigger the workflow for all branches

jobs:
  to_gitlab:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Mirror branches
        run: |
          git remote add target git@github.com:EpitechPromo2027/B-DEV-500-BER-5-1-area-etienne.namur.git
          git push target --all  # Push all branches
          git push target --tags  # Push all tags (if you want to mirror tags as well)

      - name: Clean up
        run: |
          git remote remove target
